USE master;
GO

CREATE DATABASE ACADEMY
ON
(
	NAME		= ACADEMY,
	FILENAME	= 'D:\MS SQL Server\MSSQL16.TEW_SQLEXPRESS\MSSQL\DATA\ACADEMY.mdf',
	SIZE		= 8MB,
	MAXSIZE		= 500MB,
	FILEGROWTH	= 8MB
)

LOG ON
(
	NAME		= ACADEMY_LOG,
	FILENAME	= 'D:\MS SQL Server\MSSQL16.TEW_SQLEXPRESS\MSSQL\DATA\ACADEMY.ldf',
	SIZE		= 8MB,
	MAXSIZE		= 500MB,
	FILEGROWTH	= 8MB
)
GO