USE master;
GO

CREATE DATABASE VPD_311_SQL
ON
(
	NAME		= VPD_311_SQL,
	FILENAME	= 'D:\MS SQL Server\MSSQL16.TEW_SQLEXPRESS\MSSQL\DATA\VPD_311_SQL.mdf',
	SIZE		= 8MB,
	MAXSIZE		= 500MB,
	FILEGROWTH	= 8MB
)
LOG ON
(
	NAME		= VPD_311_SQL_LOG,
	FILENAME	= 'D:\MS SQL Server\MSSQL16.TEW_SQLEXPRESS\MSSQL\DATA\VPD_311_SQL_Log.ldf',
	SIZE		= 8MB,
	MAXSIZE		= 500MB,
	FILEGROWTH	= 8MB
)
GO